const { failed } = require("../utils/errorHandler");


exports.createRating = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}

exports.updateRating = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}
exports.deleteRating = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}
exports.getAllRating = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}
exports.getProfile = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}