const { failed } = require("../utils/errorHandler");


exports.signup = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}
exports.login = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}
exports.changePassword = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}
exports.deleteUser = async(req, res)=>{
    try{

    }catch(err){
        failed(res, err);
    }
}